# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mmm.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(723, 445)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.prefixBtn = QtWidgets.QPushButton(self.centralwidget)
        self.prefixBtn.setObjectName("prefixBtn")
        self.gridLayout.addWidget(self.prefixBtn, 0, 2, 1, 1)
        self.result_nameLine = QtWidgets.QLineEdit(self.centralwidget)
        self.result_nameLine.setObjectName("result_nameLine")
        self.gridLayout.addWidget(self.result_nameLine, 3, 2, 1, 1)
        self.style_weightLine = QtWidgets.QLineEdit(self.centralwidget)
        self.style_weightLine.setObjectName("style_weightLine")
        self.gridLayout.addWidget(self.style_weightLine, 3, 1, 1, 1)
        self.runBTn = QtWidgets.QPushButton(self.centralwidget)
        self.runBTn.setObjectName("runBTn")
        self.gridLayout.addWidget(self.runBTn, 5, 1, 1, 1)
        self.contentBtn = QtWidgets.QPushButton(self.centralwidget)
        self.contentBtn.setObjectName("contentBtn")
        self.gridLayout.addWidget(self.contentBtn, 0, 0, 1, 1)
        self.contentLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contentLabel.sizePolicy().hasHeightForWidth())
        self.contentLabel.setSizePolicy(sizePolicy)
        self.contentLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.contentLabel.setTabletTracking(False)
        self.contentLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.contentLabel.setAutoFillBackground(False)
        self.contentLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.contentLabel.setObjectName("contentLabel")
        self.gridLayout.addWidget(self.contentLabel, 2, 0, 1, 1)
        self.styleLabel = QtWidgets.QLabel(self.centralwidget)
        self.styleLabel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.styleLabel.sizePolicy().hasHeightForWidth())
        self.styleLabel.setSizePolicy(sizePolicy)
        self.styleLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.styleLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.styleLabel.setObjectName("styleLabel")
        self.gridLayout.addWidget(self.styleLabel, 2, 1, 1, 1)
        self.iter_numLine = QtWidgets.QLineEdit(self.centralwidget)
        self.iter_numLine.setObjectName("iter_numLine")
        self.gridLayout.addWidget(self.iter_numLine, 4, 1, 1, 1)
        self.styleBtn = QtWidgets.QPushButton(self.centralwidget)
        self.styleBtn.setObjectName("styleBtn")
        self.gridLayout.addWidget(self.styleBtn, 0, 1, 1, 1)
        self.content_weightLine = QtWidgets.QLineEdit(self.centralwidget)
        self.content_weightLine.setEnabled(True)
        self.content_weightLine.setObjectName("content_weightLine")
        self.gridLayout.addWidget(self.content_weightLine, 3, 0, 1, 1)
        self.prefixLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prefixLabel.sizePolicy().hasHeightForWidth())
        self.prefixLabel.setSizePolicy(sizePolicy)
        self.prefixLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.prefixLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prefixLabel.setWordWrap(False)
        self.prefixLabel.setObjectName("prefixLabel")
        self.gridLayout.addWidget(self.prefixLabel, 2, 2, 1, 1)
        self.style_imageLabel = QtWidgets.QLabel(self.centralwidget)
        self.style_imageLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.style_imageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.style_imageLabel.setObjectName("style_imageLabel")
        self.gridLayout.addWidget(self.style_imageLabel, 1, 1, 1, 1)
        self.content_imageLabel = QtWidgets.QLabel(self.centralwidget)
        self.content_imageLabel.setAutoFillBackground(False)
        self.content_imageLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.content_imageLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.content_imageLabel.setLineWidth(1)
        self.content_imageLabel.setTextFormat(QtCore.Qt.PlainText)
        self.content_imageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.content_imageLabel.setObjectName("content_imageLabel")
        self.gridLayout.addWidget(self.content_imageLabel, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setLineWidth(2)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 2, 1, 1)
        self.maxLenghtLine = QtWidgets.QLineEdit(self.centralwidget)
        self.maxLenghtLine.setObjectName("maxLenghtLine")
        self.gridLayout.addWidget(self.maxLenghtLine, 4, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Style Transfer"))
        self.prefixBtn.setText(_translate("MainWindow", "result directory"))
        self.result_nameLine.setToolTip(_translate("MainWindow", "directory to save result where"))
        self.result_nameLine.setText(_translate("MainWindow", "result"))
        self.style_weightLine.setToolTip(_translate("MainWindow", "<html><head/><body><p>style picture weight</p><p>1 recommended</p></body></html>"))
        self.style_weightLine.setText(_translate("MainWindow", "1"))
        self.runBTn.setToolTip(_translate("MainWindow", "<html><head/><body><p>start the process</p></body></html>"))
        self.runBTn.setText(_translate("MainWindow", "RUN"))
        self.contentBtn.setText(_translate("MainWindow", "select content"))
        self.contentLabel.setText(_translate("MainWindow", "//content path"))
        self.styleLabel.setText(_translate("MainWindow", "//style path"))
        self.iter_numLine.setToolTip(_translate("MainWindow", "number of iterations"))
        self.iter_numLine.setText(_translate("MainWindow", "10"))
        self.styleBtn.setText(_translate("MainWindow", "select style"))
        self.content_weightLine.setToolTip(_translate("MainWindow", "<html><head/><body><p>content picture weight</p><p>1e-1 - 1e-4 recommended</p></body></html>"))
        self.content_weightLine.setText(_translate("MainWindow", "0.05"))
        self.prefixLabel.setText(_translate("MainWindow", "//result path"))
        self.style_imageLabel.setText(_translate("MainWindow", "//style image"))
        self.content_imageLabel.setText(_translate("MainWindow", "//content image"))
        self.maxLenghtLine.setToolTip(_translate("MainWindow", "<html><head/><body><p>max linear size of result picture</p><p>400 recommended on GPU</p><p>bigger it is - longer it takes </p></body></html>"))
        self.maxLenghtLine.setText(_translate("MainWindow", "200"))

